name: Check CLA
on:
  - pull_request

jobs:
  check-cla:
    runs-on: ubuntu-latest
    name: Verify contributor

    steps:
    - uses: actions/checkout@v3
    - name: Verify CLA
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: ./
